on: [push]
name: Lint
jobs:
  ecs:
    name: Easy Coding Standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v1
      - name: Easy Coding Standard Action
        run: ./vendor/bin/ecs check
      - name: PHP-CS-Fixer Action
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
      - name: Rector Action
        run: ./vendor/bin/rector process --dry-run
      - name: TLint Action
        run: ./vendor/bin/tlint lint
